### ISSUE TITLE
Force dom re-render to prevent `flip`

### ISSUE THREAD

**Issue by QoVoQ** [maoberlehner/transition-to-height-auto-with-vue#1]
Firs of all, thanks for your sharing.I've learned a lot from it.

But I found your transition height demo has a litte problem: Animation might flip occasionally.(Chrome Version 65.0.3325.181 (Official Build) (64-bit))
![ezgif com-optimize](https://user-images.githubusercontent.com/17191224/41138021-168b0372-6b11-11e8-98c0-ab0488778915.gif)

And I found the solution to that is forcing the height-animating-element to re-render(by using getComputedStyle(ele).height) before the animation starts.

And I know forcing re-render may lead to performance issues. But we can make our choice.

Here is the fixed example: https://jsbin.com/cecazuxavo/edit?html,css,js,output
And the problemtic example: https://jsbin.com/posawecibi/1/edit?html,css,js,output

**Comment by maoberlehner** [comment]
Hey @QoVoQ thanks for your feedback! I'll look into it.

**Comment by maoberlehner** [comment]
Thank you @QoVoQ for providing the solution to this problem! I've updated the code and the article accordingly!
