### ISSUE TITLE
Release as a package on npm

### ISSUE THREAD

**Issue by christophemarois** [maoberlehner/transition-to-height-auto-with-vue#2]
This library is incredible. Do you plan on releasing it as a module?

It would also make a great addition to [awesome-vue](https://github.com/vuejs/awesome-vue#readme)

**Comment by maoberlehner** [comment]
Thank you! Currently I have no time for releasing it as a module but I'd be happy if somebody else does it. Feel free to add this repository / the article to awesome-vue :)

Thanks!

**Comment by yanzijun** [comment]
@maoberlehner  I will try to wrap it up as a NPM package this weekend.

**Comment by maoberlehner** [comment]
@yanzijun cool! Let me know if I can help you.

**Comment by yanzijun** [comment]
I tried to packet it as a package. But I got problems with Vue. I try to figure difference between standalone compile and runtime build to fix these problem.

**Comment by maoberlehner** [comment]
@yanzijun you can take a look at https://github.com/chrisvfritz/hello-vue-components as a starting point!

**Comment by mesqueeb** [comment]
I'd love an NPM package as well!

**Comment by yanzijun** [comment]
I am sorry. It is so late for publishing package on NPM. It's now available download on NPM. But this is just a test. I will try to modify settings of package these days, because it can't use `Vue.use()` to register this component now.

But if you want to test it, you can try these steps:

1. Installation
`npm install --save transition-to-height-auto-with-vue`

2. To import package in your vue file
```
import TransitionExpand from 'transition-to-height-auto-with-vue'
import 'transition-to-height-auto-with-vue/dist/transition-to-height-auto-with-vue.css'
```
(The file name is a little bit long, I would try to rename it in next version.)

3. To register component
```
export default {
  name: 'HelloWorld',
  components: {
    TransitionExpand
  },
 ...
}
```

4. To use this component
```
<transition-expand>
      <div v-if="show" class="box">
        123
      </div>
</transition-expand>
```

I would try to rename css file name, and install with `Vue.use` globally. After that, I would send a PR request to modify `README.md`.

**Comment by yanzijun** [comment]
Hi everyone, I has already modified some settings. And now it's available download from NPM.
I rename the NPM package. And now you can register component globally.

### Installation
```bash
npm install --save vue-transition-expand
```

### Registration

#### Globally
```javascript
import TransitionExpand from 'vue-transition-expand'
import 'vue-transition-expand/dist/vue-transition-expand.css'

Vue.use(TransitionExpand)
```

#### SFC

```javascript
import {TransitionExpand} from 'vue-transition-expand'
import 'vue-transition-expand/dist/vue-transition-expand.css'

export default {
  name: 'HelloWorld',
  components: {
    TransitionExpand
  },
  data () {
    return {
    }
  }
}
```

**Comment by mesqueeb** [comment]
@maoberlehner could you audit the package and give your word of approval? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yanzijun** [comment]
@maoberlehner Could you provide me your NPM username ? I would invite you to manage this package.

**Comment by maoberlehner** [comment]
@yanzijun https://www.npmjs.com/~maoberlehner ;)

@mesqueeb & @yanzijun code looks ok but @yanzijun you absolutely should add your own README and don't link to this GitHub repository in the `homepage` and `repository` sections but instead create your own GitHub repository for the package.
