### ISSUE TITLE
IE11 is not working

### ISSUE THREAD

**Issue by sowinski** [maoberlehner/transition-to-height-auto-with-vue#4]
Great Work!

As usual IE11 is doing strange stuff ...

Your example is not working on IE11 => [https://transition-to-height-auto-with-vue.netlify.com/](https://transition-to-height-auto-with-vue.netlify.com/)

Any idea what is wrong? 

Cheers

**Comment by fedepasquarelli** [comment]
the problem on IE is given by this part:
`element.style.width = null;
          element.style.position = null;
          element.style.visibility = null;`
if instead of null you reset the inline style using
`element.style.width = '';
          element.style.position = '';
          element.style.visibility = '';`
it should work on IE11 also. or at least i fixed the issue this way

**Comment by maoberlehner** [comment]
@fedepasquarelli is right.
See: https://github.com/maoberlehner/transition-to-height-auto-with-vue/issues/3
