### ISSUE TITLE
style scoped

### ISSUE THREAD

**Issue by 719media** [maoberlehner/transition-to-height-auto-with-vue#5]
https://github.com/maoberlehner/transition-to-height-auto-with-vue/blob/master/src/components/TransitionExpand.vue#L68-L75

I'm not sure this styling does anything?
The style is scoped, and yet this component will not have any nodes in DOM, so this will never apply to anything?

**Comment by maoberlehner** [comment]
Yes.

> However, a child component's root node will be affected by both **the parent's scoped CSS and the child's scoped CSS.**

https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements
